---
all:
  vars:
    ansible_user: ivalice
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: /root/.ssh/ivalice-cluster
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  children:
    cluster:
      children:
        head:
        workers:
    head:
      hosts:
        dalmasca:
          ansible_host: 10.42.0.1
          ansible_connection: local
          ansible_become: true
    workers:
      hosts:
        archadia:
          ansible_host: 10.42.0.11
        rozarria:
          ansible_host: 10.42.0.12
        bhujerba:
          ansible_host: 10.42.0.13
        nabradia:
          ansible_host: 10.42.0.14
        kerwon:
          ansible_host: 10.42.0.15
